### ISSUE TITLE
Add benchmarks?

### ISSUE THREAD

**Issue by rubybb** [cfworker/cfworker#108]
I'd love to see actual comparisons for the libraries compared to their originals.

**Comment by jdanyow** [comment]
@rubybb could you clarify this request? Which packages do you want to compare?

I've added `@cfworker/json-schema` to the [benchmark referenced on the json-schema site](https://json-schema.org/implementations.html#benchmarks:~:text=json%2Dschema%2Dbenchmark%20%2D%20an%20independent%20benchmark%20for,based%20on%20JSON%2DSchema%20Test%20Suite%20(MIT)). As noted in it's readme, it's slow because it does not use code generation (eval/new Function are not available in workers).  It's [among the most spec compliant](https://github.com/ebdrup/json-schema-benchmark#test-failure-summary) however.

**Comment by rubybb** [comment]
Ah, I was just wondering if you could standardize releasing benchmarks for all packages compared to their usual. As packages like "jwt" work in most serverless containers the benefits are not really seen if not in benchmarks.

**Comment by jdanyow** [comment]
Ah, something like `@cfworker/jwt` isn't competing on performance although I'm sure it's the fastest for *it's target runtime*. For example, `jsonwebtoken` by Auth0 is by far the most popular lib for working with JWTs *on node*. It depends on `jws` -> `jwa` -> `crypto`, node buffers, node streams, etc. It's not well suited for use in Cloudflare workers because they don't have node buffers, node streams, or the node crypto module. The reason `@cfworker/jwt` exists is to provide a solution that uses web crypto and minimize dependences / compiled code size to avoid exceeding the Cloudflare worker script limits.
