### ISSUE TITLE
Support for secrets and vars

### ISSUE THREAD

**Issue by dgitq** [cfworker/cfworker#124]
Hi and thanks a lot for these packages! Trying out the dev package but I stumbled since my worker is using vars and secrets as per the documentation: 
https://developers.cloudflare.com/workers/cli-wrangler/configuration#vars
https://developers.cloudflare.com/workers/cli-wrangler/commands#secret

I guess I always can set vars as global variables but how to handle secrets, any suggestions ? Or do you have plans to support this?

**Comment by jdanyow** [comment]
I'd like to go back and implement support for secrets/vars as part of work to support wrangler.toml configuration. I haven't had the bandwidth to pick that work up lately.

I'm currently using .env files to define secrets locally for development. Then I use a different set of production secrets [in github](https://docs.github.com/en/actions/reference/encrypted-secrets). In both cases cfworker dev enables accessing the values via `process.env.SECRET`. Here's an example:
- Secret definition in env: https://github.com/cfworker/cfworker/blob/master/.github/workflows/build.yml#L17-L20
- Secret usage: https://github.com/cfworker/cfworker/blob/master/packages/cosmos/test/client.integration.spec.ts#L13-L15

This isn't quite as good as using the secrets feature cloudflare provides because the values are ultimately compiled into your code by cfworker dev.

Here's the code in cfworker dev where `process.env.SECRET_XYZ` is replaced with the env value:
- https://github.com/cfworker/cfworker/blob/master/packages/dev/src/bundler.js#L18
- https://github.com/cfworker/cfworker/blob/master/packages/dev/src/bundler.js#L121

**Comment by dgitq** [comment]
Thanks for your quick response, will look into that! 👍 Yea I agree that the secrets should not be in the repos or baked into the code during build time. Even if I switch to Key Vault or similar I would need to store some credential to access the vault, and we're effectively back to square one.
