### ISSUE TITLE
[Question] JWT Cache

### ISSUE THREAD

**Issue by timonmasberg** [cfworker/cfworker#191]
https://github.com/cfworker/cfworker/blob/main/packages/jwt/src/jwks.ts

I am not very familiar with workers, but the `importedKeys` are not a durable object right? We need some persistent cache for that, such as Cloudflare KVs? Or do I understand it wrong because otherwise I don't get the need for keeping `importedKeys` for each request? Maybe the design idea behind this is to always call `importKey` before verifying a JWT?

Thanks in advance!

**Comment by timonmasberg** [comment]
Is extending this with a persistent storage of interest? Or do you think this should be handled by the caller (importing the key(s) from KV).

**Comment by jdanyow** [comment]
I think it would be best to leave it up to the caller. In fact, I probably should have delegated the key fetching rather than forcing the default [automatic jwks fetching behavior](https://github.com/cfworker/cfworker/blob/main/packages/jwt/src/jwks.ts#L57) on everyone. Persistent storage could be implemented with today's lib like this:
```ts
import { getJwks, importKey } from '@cfworker/jwt';

const issuer = '...';

let jwks = await ... fetch keyset from persistent storage ...;
if (!jwks) {
  jwks = await getJwks(issuer); // or use your own method of fetching the keyset
}
await await Promise.all(jwks.keys.map(jwk => importKey(issuer, jwk)));
```

**Comment by timonmasberg** [comment]
Thanks for the example!
