### ISSUE TITLE
Option to extend the rollup config

### ISSUE THREAD

**Issue by jonatansberg** [cfworker/cfworker#31]
Hey @jdanyow, 
I love what you're doing here. The code is well structured, and everything is really neat and easy to follow. Great work! 

I've been looking in to building a small web app framework on top of the web, web-router and dev packages and Svelte. I've come to the conclusion that on order to do so I'd need to extend the rollup config quite a bit. Ideally I would also need an additional build pipeline for client side assets.

Is this something that's in line with your extended vision for this project? Or do you think I'd be better off forking the dev package to build something on my own?

I've already cobbled together a super hacky version of what I'm trying to do using [FAB](fab.dev) and [Sapper](https://sapper.svelte.dev/), but I'm leaning towards replacing the Sapper-part with something leaner and more purpose built based on what you have done here. Packaging the final output as a FAB would still leave me with a lot of possible deployment targets, with CF Workers being the main one.

Cheers!

**Comment by jdanyow** [comment]
Hey :wave: thanks for the kind words!

The dev package only exists because I didn't like Wrangler's debugging or bundling capabilities. Hopefully Wrangler gets better but in the meantime dev has been working for my use cases.

Word of caution, `@cfworker/dev`'s usage of headless chrome to simulate the worker has proven to be a bit cludgy in a few areas:
1. [Guarding the scope](https://github.com/cfworker/cfworker/blob/master/packages/dev/src/runtime/index.js#L11-L26) to only APIs available in workers.
2. There are some limitations with respect to [forbidden headers](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) that I've [patched](https://github.com/cfworker/cfworker/blob/master/packages/dev/src/runtime/headers.js) for the most part.
3. [Marshalling the request/responses](https://github.com/cfworker/cfworker/blob/master/packages/dev/src/worker-host.js#L94-L149) across the node/puppeteer boundaries could be improved.

The package lacks worker features like key/value storage, etc. I'm not certain that dev will be sustainable as workers features evolve. I'm also thinking it might make sense to use Deno instead of headless chrome to avoid the issues I described above. Waiting to see how things play out with Deno and keeping an eye on some Deno issues like this one:
https://github.com/denoland/deno/issues/1891#issuecomment-629691599

I think your best bet would be to fork because the dev package may undergo a big refactor. The rest of the packages are really starting to stabilize. Hopefully all that makes sense!
