### ISSUE TITLE
Documentation on how to deploy static site

### ISSUE THREAD

**Issue by duffn** [cfworker/cfworker#70]
First, thanks for these utilities.

I'm having difficulty figuring out how to deploy a simple static site. What should I be passing into the `--site` argument? I have my static site build locally and in a `public` directory in the cwd. 

```
./node_modules/.bin/cfworker deploy-dev -s public
```

results in 

```
✖ Error: Could not load rollup:plugin-multi-entry:entry-point: invalid glob pattern:
```

I'm happy to open a PR for the README if I can figure out how to properly pass in my static site directory.

**Comment by jdanyow** [comment]
Wrangler sites creates a worker script that uses `@cloudflare/kv-asset-handler`. The script looks like this: https://github.com/cloudflare/kv-asset-handler#return

cfworker doesn't generate a site worker script so you'd need to create one using the example above. Assuming you created a worker script matching the example and the script was at `./path/to/worker.js` then the following command should work:

```
cfworker run ./path/to/worker.js --site ./path/to/site/folder --watch --inspect
```

I've not tried this to be honest, I don't use `@cloudflare/kv-asset-handler` in my applications due to some custom requirements, however cfworker's deploy logic was written to be compatible with `@cloudflare/kv-asset-handler`'s manifest format, kv key format, and default bindings:
- https://github.com/cloudflare/kv-asset-handler/blob/master/src/index.ts#L5
- https://github.com/cfworker/cfworker/blob/b2d921a737098a89d1c51fe4e89b1c783be73620/packages/dev/src/cloudflare-api.js#L366-L377

**Comment by duffn** [comment]
Thank you, this worked! Well, nearly.

With your direction, here's what I did for others to reference.

- `wrangler init --site my-site-name`.
- Took the contents of `index.js` in `workers-site` from the files generated by the above command.
- Created a `worker.js` file with the above contents (you can just as easily use the created `index.js` file itself).
- Built my static site into the `public` directory.
- `./node_modules/.bin/cfworker deploy-dev ./worker.js --site ./public`

This resulted in deploying my static site correctly to my dev domain on Cloudflare workers. 🎉 

However, this little deploy button was not checked, requiring me to manually check it in order to fully deploy and visit my site.

![Screen Shot 2020-08-28 at 8 14 57 AM](https://user-images.githubusercontent.com/3457341/91578263-27ccd680-e907-11ea-804a-5a9dc30f7984.png)

I'm going to look through the codebase to see if I can locate where this would happen, but would take any direction if you have it.

Thanks!

**Comment by jdanyow** [comment]
@duffn nice work! Looks like cfworker is missing this step:

https://github.com/cloudflare/wrangler/blob/7798fb04242fc58e8e58c98087bd40b04a126134/src/deploy/mod.rs#L52-L64

(posting `{ enabled: true }`) 

Probably goes here in the deploy code, apologies this area isn't very tidy :grimacing: 
https://github.com/cfworker/cfworker/blob/master/packages/dev/src/cloudflare-api.js#L94
